services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testecep
    ports:
      - "3306:3306"

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    image: cepfinder/api:v1
    ports:
      - "8080:80"
    volumes:
      - ./src/api:/app
    entrypoint: [ "/bin/sh", "/app/entrypoint.sh" ]

    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: testecep

  web:
    image: cepfinder/web:v1
    depends_on:
      - api
    build: .
    ports:
      - "9090:80"
